# Generated by Django 3.1 on 2020-08-19 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200818_2146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wyszukaj',
            new_name='Search',
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
        migrations.RenameField(
            model_name='search',
            old_name='wyszukaj',
            new_name='search',
        ),
    ]
